@BASE_URL=http://localhost:3002/warehouse/api/v1

### Get Inventory
GET {{BASE_URL}}/inventory HTTP/1.1
Content-Type: application/json

### Get Purchases
GET {{BASE_URL}}/purchases HTTP/1.1
Content-Type: application/json

### Get test sqs
POST {{BASE_URL}}/test-sqs HTTP/1.1
Content-Type: application/json

{
  "orderId": "154e323b-35e2-45c6-996a-20bf46af8a27",
  "ingredients": [
    { "id": 9, "quantity": 500 },
    { "id": 4, "quantity": 300 },
    { "id": 1, "quantity": 3 },
    { "id": 7, "quantity": 1 },
    { "id": 6, "quantity": 30 }
  ],
  "action": "REQUEST_INGREDIENTS"
}