service: warehouse-service-v3

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${env:STAGE}
  environment:
    DYNAMODB_TABLE_INVENTORY: ${env:DYNAMODB_TABLE_INVENTORY}
    DYNAMODB_TABLE_PURCHASES: ${env:DYNAMODB_TABLE_PURCHASES}
    SQS_RESPONSE_QUEUE: ${env:SQS_RESPONSE_QUEUE} # where warehouse sends the ingredients
    SQS_REQUEST_QUEUE: ${env:SQS_REQUEST_QUEUE} # where kitchen asks for ingredients / warehouse receives the order ingredients

functions:
  sqsListener:
    handler: dist/lambda.sqsHandler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:123456789012:${env:SQS_REQUEST_QUEUE}

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-monorepo
resources:
  - ${file(../aws-resources/gateway-response.yml)}
