service: warehouse-service-v4

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  environment:
    DYNAMODB_TABLE_INVENTORY: !Ref InventoryTable
    DYNAMODB_TABLE_PURCHASES: !Ref PurchasesTable
    # SQS_RESPONSE_QUEUE: !Ref IngredientsResponseQueue
    # SQS_REQUEST_QUEUE: !Ref IngredientsRequestQueue
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource:
            - "*"

        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "*"

  apiGateway:
    restApiId: ${cf:free-launch-api-monorepo-v3-dev.ApiGatewayRestApiId}
    restApiRootResourceId: ${cf:free-launch-api-monorepo-v3-dev.ApiGatewayRestApiRootResourceId}

functions:
  warehouseApi:
    handler: src/lambda.handler
    events:
      - http:
          path: /warehouse/purchases
          method: get
      - http:
          path: /warehouse/inventory
          method: get

  # sqsListener:
  #   handler: src/lambda.sqsHandler
  #   events:
  #     - sqs:
  #         # arn: ${cf:free-launch-api-monorepo-dev.RequestQueueArn}
  #         arn: ${cf:free-launch-api-monorepo-v3-dev.RequestQueueArn}
  #         batchSize: 1

resources:
  Resources:
    # DynamoDB Tables
    InventoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: warehouse-inventory-table-v4
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    PurchasesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: warehouse-purchases-table-v4
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-monorepo
