service: warehouse-service-v4

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  environment:
    DYNAMODB_TABLE_INVENTORY: !Ref InventoryTable
    DYNAMODB_TABLE_PURCHASES: !Ref PurchasesTable
    SQS_RESPONSE_QUEUE_URL: ${cf:free-launch-api-monorepo-v3-dev.ResponseQueueUrl}
    SQS_REQUEST_QUEUE_URL: ${cf:free-launch-api-monorepo-v3-dev.RequestQueueUrl}
    REGION : ${self:provider.region}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource:
            - "*"

        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "*"

  apiGateway:
    restApiId: ${cf:free-launch-api-monorepo-v3-dev.ApiGatewayRestApiId}
    restApiRootResourceId: ${cf:free-launch-api-monorepo-v3-dev.ApiGatewayRestApiRootResourceId}

functions:
  warehouseApi:
    handler: src/lambda.handler
    description: "Warehouse API"
    timeout: 30
    events:
      - http:
          path: /warehouse/api/v1/purchases
          method: get
      - http:
          path: /warehouse/api/v1/inventory
          method: get

  sqsListener:
    handler: src/lambda.sqsHandler
    description: "Listen to the request queue"
    timeout: 60
    events:
      - sqs:
          arn: ${cf:free-launch-api-monorepo-v3-dev.RequestQueueArn}
          batchSize: 1

resources:
  Resources:
    # DynamoDB Tables
    InventoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: warehouse-inventory-table-v4
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    PurchasesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: warehouse-purchases-table-v4
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-monorepo
