@BASE_URL=http://localhost:3009/api/v1
# @BASE_URL=https://kh1fur7kdd.execute-api.us-east-1.amazonaws.com/dev/api/v1/kitchen

### test
GET http://localhost:3001/api/v1/orders?status=CREATED HTTP/1.1
Content-Type: application/json
### Create Orders
POST {{BASE_URL}}/orders HTTP/1.1
Content-Type: application/json

{
    "quantity": "2",
    "notes": "Para los niños pobres"
}

### Get Requests
GET {{BASE_URL}}/requests HTTP/1.1
Content-Type: application/json

### Get order by status
@status=IN_PROGRESS
# @status=READY
@status=CREATED
GET {{BASE_URL}}/orders?status={{status}} HTTP/1.1
Content-Type: application/json

### Get Recipes
GET {{BASE_URL}}/recipes HTTP/1.1
Content-Type: application/json
