service: kitchen-service

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  profile: free-launch
  stage: dev
  environment:
    PG_HOST: ${env:PG_HOST}
    PG_USER: ${env:PG_USER}
    PG_PASSWORD: ${env:PG_PASSWORD}
    PG_DATABASE: ${env:PG_DATABASE}
    SQS_REQUEST_QUEUE: ${cf:warehouse-service-${self:provider.stage}.RequestQueueUrl}
    SQS_RESPONSE_QUEUE: ${cf:warehouse-service-${self:provider.stage}.ResponseQueueUrl}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource:
            - ${cf:warehouse-service-${self:provider.stage}.RequestQueueArn}
            - ${cf:warehouse-service-${self:provider.stage}.ResponseQueueArn}

functions:
  api:
    handler: src/lambda.handler
    events:
      - httpApi:
          path: /orders
          method: post
      - httpApi:
          path: /orders
          method: get

  sqsListener:
    handler: src/lambda.sqsHandler
    events:
      - sqs:
          arn: ${cf:warehouse-service-${self:provider.stage}.ResponseQueueArn}
          batchSize: 1

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
